version: 2
jobs:
  build:
    docker:
      - image: rust
    steps:
      - run: apt -y update --fix-missing
      - run: apt -y install cmake
      - checkout
      - run: git submodule update --init --recursive
      - run: cargo build
      - run: cd examples && ./test.sh
