version: 2
jobs:
  build:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: cargo build
      - run: |
          rustup component add clippy
          cargo clippy
      - run: cd examples && ./test.sh
